# Generated by Django 5.2.9 on 2026-01-11 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=255)),
                ('square_meters', models.IntegerField()),
                ('is_rented', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('vacant', 'Vacant'), ('rented', 'Rented'), ('maintenance', 'Maintenance')], default='vacant', max_length=20)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
