# Generated by Django 5.2.9 on 2026-01-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('detached', 'Detached'), ('office', 'Office'), ('land', 'Land/Plot')], default='apartment', max_length=30),
        ),
    ]
