# Generated by Django 5.2.9 on 2026-01-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_document_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Μετρητά'), ('bank_transfer', 'Τραπεζική Μεταφορά'), ('check', 'Επιταγή'), ('card', 'Κάρτα'), ('other', 'Άλλο')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='receipt_number',
            field=models.CharField(blank=True, help_text='Αριθμός απόδειξης ή αναφοράς μεταφοράς', max_length=100),
        ),
    ]
