# Generated by Django 5.2.9 on 2026-01-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_rentpayment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('overdue_payment', 'Overdue Payment'), ('contract_ending', 'Contract Ending'), ('contract_starting', 'Contract Starting'), ('payment_due', 'Payment Due'), ('payment_received', 'Payment Received'), ('other', 'Other')], max_length=30),
        ),
    ]
