# Generated by Django 5.2.9 on 2026-01-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0007_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='payment_due_day',
            field=models.IntegerField(default=5, help_text='Η μέρα του μήνα που καταβάλλεται το ενοίκιο (1-31)'),
        ),
    ]
